### ISSUE TITLE
Issue with PHP rewrite

### ISSUE THREAD

**Issue by nhanledev** [QROkes/webinoly#18]
https://github.com/QROkes/webinoly/blob/0e572f6bc8a6a667c2cfe1dda61ce0fdaedcedeb/templates/nginx/common/php.conf#L4

I update Webinoly from v1.6.2 to v1.7.0. All the sites are not accessible and return 404 error except the index page.

I rechecked the config file and noticed that the location file above has `$uri =404` in the `location /`.

I removed that part and all the sites work normally. I do not know if this is a feature or a bug?

**Comment by QROkes** [comment]
**Hi nhanledev,**

Yes, we add this line in the last update because by default Nginx don't throw this error as expected.

In most of the cases I haven't seen issues, but you are the second person reporting this issue, I still don't understand why it can become not accesible a complete site. Seems like it's related to an specific site configuration.

Regards.

**Comment by nhanledev** [comment]
Hello QROkes,

I have tested v1.7.0 on 3 different Ubuntu 18.04 VPSes and Windows's WSL (all are in latest update) with `nginx/1.15.6` and none of them pass your new setting.

I encountered this problem when I was installing a brand new WP site (no custom config) with `site mydomain.com -php`.

**Comment by nhanledev** [comment]
Hello QROkes,

I tested your command and it does not work too.
I have sent you an email contains the credential of the whole site. Please take a look.

Thank you.

**Comment by QROkes** [comment]
Fixed in v1.7.1
Thanks for your help!
